version: '3'

services:
  client:
    image: 'carlanders/callme-client'
    build:
      dockerfile: Dockerfile.dev
      context: ./callme-client
    environment:
      - REACT_APP_API_HOSTNAME=localhost:12345

  user:
    image: 'carlanders/callme-services-user-service'
    depends_on:
      - postgres
    environment:
      - DB_HOST_PORT=postgres:5432
      - DB_PASS=password
      - DB_USER=user
      - JWT_EXPIRE_MS=86400000
      - JWT_SECRET=secret

  status:
    image: 'carlanders/callme-services-status-service'
    depends_on:
      - redis
    environment:
      - REDIS_HOSTNAME=redis
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - USER_STATUS_TTL=30000

  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  redis:
    image: 'redis'
    command: redis-server --requirepass password

  nginx:
    depends_on:
      - user
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '12345:80'