server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST_PORT}/call
    username: ${DB_USER}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false